#!/usr/bin/env python3
"""
Fine-tune a PyroSight detector on real fireground imagery.

YOLO-World is open-vocabulary: it matches text prompts against pixels and it
is genuinely impressive that it works at all, but it is guessing from a
description. It has never seen a fire-service door, an emergency exit sign
through smoke, or a firefighter in full PPE, and it cannot be made pinpoint
by tuning thresholds — the ceiling is the model, not the gates in front of
it. A YOLOv8 fine-tuned on a few thousand labelled fireground frames beats it
decisively, and runs far faster on the Pi.

    # 1. scaffold the dataset (once)
    python backend/scripts/train.py --init

    # 2. put images + YOLO-format labels in the folders it prints, then
    python backend/scripts/train.py --epochs 100

    # 3. it exports ONNX + sidecar automatically; the backend picks them up
    #    on next start with no code change.

Class order comes from vision/classes.TRAINABLE_CLASSES and is written into
data.yaml, the model, and the sidecar from that one list — see the note there
for why that matters more than it looks.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
PROJECT = BACKEND.parent
MODELS_DIR = BACKEND / "models"
DATASET = PROJECT / "dataset"
sys.path.insert(0, str(BACKEND))

from pyrosight.vision import classes as taxonomy  # noqa: E402

SPLITS = ("train", "val")
CLASSES = list(taxonomy.TRAINABLE_CLASSES)

# Below this the run is not worth the electricity. Fine-tuning from COCO
# weights needs far less data than training from scratch, but a class with a
# handful of examples produces a detector that is confidently wrong about it,
# which is worse than the open-vocabulary model it replaces.
MIN_IMAGES_PER_CLASS = 50
MIN_TOTAL_IMAGES = 200


def data_yaml_text() -> str:
    names = "\n".join(f"  {i}: {n}" for i, n in enumerate(CLASSES))
    return (
        "# GENERATED by backend/scripts/train.py — do not hand-edit the class\n"
        "# list. Order must match vision/classes.TRAINABLE_CLASSES exactly or\n"
        "# the exported model's indices will not match the .classes.txt\n"
        "# sidecar, and every detection will come back under the wrong label.\n"
        f"path: {DATASET}\n"
        "train: images/train\n"
        "val: images/val\n"
        "\n"
        "names:\n" + names + "\n"
    )


def cmd_init() -> int:
    for split in SPLITS:
        (DATASET / "images" / split).mkdir(parents=True, exist_ok=True)
        (DATASET / "labels" / split).mkdir(parents=True, exist_ok=True)
    (DATASET / "data.yaml").write_text(data_yaml_text())

    print(f"[OK] dataset scaffolded at {DATASET}\n")
    print("Put your data here:")
    for split in SPLITS:
        print(f"  {DATASET / 'images' / split}/   .jpg / .png frames")
        print(f"  {DATASET / 'labels' / split}/   matching .txt, one per image")
    print("\nLabel format — one line per object, normalised 0-1:")
    print("  <class_id> <x_center> <y_center> <width> <height>\n")
    print("Class ids:")
    for i, n in enumerate(CLASSES):
        print(f"  {i}  {n}")
    print("\nRoughly 80/20 train/val. Label with Roboflow, Label Studio or")
    print("CVAT — all three export YOLO format directly.")
    return 0


def _count(split: str) -> int:
    d = DATASET / "images" / split
    if not d.exists():
        return 0
    return sum(1 for p in d.iterdir()
               if p.suffix.lower() in (".jpg", ".jpeg", ".png"))


def _class_histogram() -> dict:
    """How many labelled instances exist per class, across both splits."""
    hist = {n: 0 for n in CLASSES}
    for split in SPLITS:
        d = DATASET / "labels" / split
        if not d.exists():
            continue
        for txt in d.glob("*.txt"):
            for line in txt.read_text().splitlines():
                parts = line.split()
                if not parts:
                    continue
                try:
                    idx = int(parts[0])
                except ValueError:
                    continue
                if 0 <= idx < len(CLASSES):
                    hist[CLASSES[idx]] += 1
    return hist


def cmd_train(args) -> int:
    if not (DATASET / "data.yaml").exists():
        print("[ERR] no dataset. Run:  python backend/scripts/train.py --init")
        return 1

    # Rewrite data.yaml every run: the taxonomy is the source of truth, and a
    # stale hand-edited copy is the one failure mode that produces a working
    # model with silently swapped labels.
    (DATASET / "data.yaml").write_text(data_yaml_text())

    n_train, n_val = _count("train"), _count("val")
    print(f"[..] {n_train} training images, {n_val} validation images")
    if n_train == 0:
        print(f"[ERR] no images in {DATASET / 'images' / 'train'}")
        return 1
    if n_val == 0:
        print(f"[ERR] no images in {DATASET / 'images' / 'val'} — without a "
              "held-out split the reported accuracy is meaningless")
        return 1

    hist = _class_histogram()
    print("[..] labelled instances per class:")
    thin = []
    for n in CLASSES:
        flag = ""
        if hist[n] == 0:
            flag = "  <- NONE, will never be detected"
            thin.append(n)
        elif hist[n] < MIN_IMAGES_PER_CLASS:
            flag = f"  <- thin (< {MIN_IMAGES_PER_CLASS})"
            thin.append(n)
        print(f"       {n:<13} {hist[n]:>5}{flag}")

    total = n_train + n_val
    if total < MIN_TOTAL_IMAGES and not args.force:
        print(f"\n[ERR] {total} images is below the {MIN_TOTAL_IMAGES} floor. A "
              "model trained on this will be confidently wrong, which is worse\n"
              "      than the open-vocabulary detector it replaces. --force to "
              "override.")
        return 1
    if thin and not args.force:
        print(f"\n[WARN] thin classes: {', '.join(thin)}")
        print("       Training anyway; expect these to underperform "
              "YOLO-World.\n")

    try:
        from ultralytics import YOLO
    except ImportError:
        print("[ERR] pip install ultralytics")
        return 1

    print(f"[..] fine-tuning {args.base} for {args.epochs} epochs @ {args.imgsz}px")
    model = YOLO(args.base)
    model.train(
        data=str(DATASET / "data.yaml"),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        project=str(PROJECT / "runs"),
        name="pyrosight",
        exist_ok=True,
        # Fireground imagery is dark, smoky and low-contrast. These augments
        # widen that distribution rather than the geometric ones that matter
        # less here — a victim is a victim upside down, but a victim at half
        # brightness through smoke is what the model will actually meet.
        hsv_v=0.5,
        hsv_s=0.5,
        degrees=8.0,
        fliplr=0.5,
        mosaic=1.0,
    )

    print("\n[..] validating on the held-out split")
    metrics = model.val()
    _report(metrics)

    if args.no_export:
        return 0
    return _export(model, args.imgsz)


def _report(metrics) -> None:
    """Per-class accuracy. The summary number hides the class that matters."""
    try:
        maps = metrics.box.maps           # mAP50-95 per class
        print("\n  class          mAP50-95")
        for i, n in enumerate(CLASSES):
            if i < len(maps):
                print(f"  {n:<13} {maps[i]:>8.3f}")
        print(f"\n  overall mAP50    {metrics.box.map50:.3f}")
        print(f"  overall mAP50-95 {metrics.box.map:.3f}")
    except Exception:  # noqa: BLE001 - metrics shape varies by version
        print("  (per-class metrics unavailable for this ultralytics version)")


def _export(model, imgsz: int) -> int:
    MODELS_DIR.mkdir(exist_ok=True)
    print("\n[..] exporting ONNX for the Pi runtime")
    try:
        out = model.export(format="onnx", imgsz=imgsz, simplify=True, opset=19)
    except Exception as exc:  # noqa: BLE001
        print(f"[ERR] export failed: {exc}")
        return 1

    # yolov8n.onnx is the canonical filename VisionConfig.onnx_model points at,
    # so dropping it here is the entire "deploy" step.
    target = MODELS_DIR / "yolov8n.onnx"
    shutil.copyfile(out, target)
    target.with_suffix(".classes.txt").write_text("\n".join(CLASSES) + "\n")

    print(f"[OK] {target}  ({target.stat().st_size / 1e6:.1f} MB)")
    print(f"[OK] {target.with_suffix('.classes.txt')}  ({len(CLASSES)} classes)")
    print("\nRestart the backend. The detector chain prefers ONNX, so it will")
    print("pick this up over YOLO-World automatically — check /api/health")
    print("reports  \"detector\": \"onnx\".")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--init", action="store_true",
                   help="scaffold the dataset folders and data.yaml, then exit")
    p.add_argument("--base", default="yolov8n.pt",
                   help="starting weights (yolov8n/s/m.pt). n is the Pi target")
    p.add_argument("--epochs", type=int, default=100)
    p.add_argument("--imgsz", type=int, default=416,
                   help="must match VisionConfig.input_size")
    p.add_argument("--batch", type=int, default=16)
    p.add_argument("--device", default=None,
                   help="cpu, mps (Apple GPU), 0 (CUDA). default: auto")
    p.add_argument("--no-export", action="store_true",
                   help="train and validate only, skip the ONNX export")
    p.add_argument("--force", action="store_true",
                   help="train despite too little data")
    args = p.parse_args()

    if args.init:
        return cmd_init()
    return cmd_train(args)


if __name__ == "__main__":
    sys.exit(main())
